### ISSUE TITLE
Appendices

### ISSUE THREAD

**Issue by lmullen** [chnm/crdh#8]
We need a mechanism for listing the various appendices that authors want to include with their articles. These appendices will just be files available for download, so they do not need any special display. I'm not sure where best to put them on the article page---before or after the notes and bibliography?

Here is a suggested format for listing the appendices

```
appendix:
- name: README
  file: catalano-v01/README.txt
- name: Data archive
  file: catalano-v01/catalano-data.zip
```

which would result in something like this (probably with the `download` attribute):

```
<ul>
  <li><a href="/SOMEPATH/catalano-v01/README.txt" download>README</a></li>
  <li><a href="/SOMEPATH/catalano-v01/catalano-data.zip" download>Data archive</a></li>
</ul>
```

Where should the files be stored? If in the repository, how will we handle very large files?
